#ifndef COMMOMMODEL_GLOBAL_H
#define COMMOMMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMOMMODEL_LIBRARY)
#  define PLUGINCONFIGURATION_EXPORT Q_DECL_EXPORT
#  define PUMPPLUGINFUNCTION_EXPORT Q_DECL_EXPORT
#  define VALVEPLUGINGROUTINGFUNCTION_EXPORT Q_DECL_EXPORT
#  define FUNCTIONSET_EXPORT Q_DECL_EXPORT
#  define HEATFUNCTION_EXPORT Q_DECL_EXPORT
#  define LIGHTFUNCTION_EXPORT Q_DECL_EXPORT
#  define MEASUREOD_EXPORT Q_DECL_EXPORT
#  define STIRFUNCTION_EXPORT Q_DECL_EXPORT
#  define MEASURETEMPERATUREFUNCTION_EXPORT Q_DECL_EXPORT
#  define MEASURELUMINISCENCEFUNCTION_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINCONFIGURATION_EXPORT Q_DECL_IMPORT
#  define PUMPPLUGINFUNCTION_EXPORT Q_DECL_IMPORT
#  define VALVEPLUGINGROUTINGFUNCTION_EXPORT Q_DECL_IMPORT
#  define FUNCTIONSET_EXPORT Q_DECL_IMPORT
#  define HEATFUNCTION_EXPORT Q_DECL_IMPORT
#  define LIGHTFUNCTION_EXPORT Q_DECL_IMPORT
#  define MEASUREOD_EXPORT Q_DECL_IMPORT
#  define STIRFUNCTION_EXPORT Q_DECL_IMPORT
#  define MEASURETEMPERATUREFUNCTION_EXPORT Q_DECL_IMPORT
#  define MEASURELUMINISCENCEFUNCTION_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMOMMODEL_GLOBAL_H
