#ifndef COMMOMMODEL_GLOBAL_H
#define COMMOMMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMOMMODEL_LIBRARY)
#  define COMMOMMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMOMMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMOMMODEL_GLOBAL_H
